### PR TITLE
Initial webapp setup first commit.

### PR DESCRIPTION
**Pull request by kshitijbhardwaj**
Signed-off-by: kshitij <kshtj21@hotmail.com>

### CODE REVIEW

**Comment by kshitijbhardwaj** [comment]
Angular setup done. Development needs to be started

**Comment by bevanamit** [comment]
Will have initial screen today?

**Comment by theheapdump** [comment]
awesome @kshitijbhardwaj

**Comment by kshitijbhardwaj** [comment]
@bevanamit No man working on it. Lets see

**Pull request merged**
